from __future__ import annotations

from pathlib import Path
from typing import Any

FALLBACK_PATH = Path(__file__).parent / "pricing_fallback.json"

CATALOG_SHORTLIST = (
    "gpt-4o",
    "gpt-4o-mini",
    "o1-mini",
    "claude-3-5-sonnet-20241022",
    "claude-3-5-haiku-20241022",
    "claude-3-opus-20240229",
    "gemini-1.5-pro",
    "gemini-1.5-flash",
    "mistral-large-latest",
    "llama-3.1-70b-instruct",
)

# Preset groups

from .presets_fallback import FALLBACK_PRESETS
PRESETS: dict[str, list[dict[str, Any]]] = {
    "anthropic": [
        {
            "id": "claude-3-7-sonnet-20250219",
            "provider": "anthropic",
            "price_in": 3.0,
            "price_out": 15.0,
            "api_key_env": "ANTHROPIC_API_KEY",
            "capability_score": 0.5,
        },
        {
            "id": "claude-3-5-sonnet-20241022",
            "provider": "anthropic",
            "price_in": 3.0,
            "price_out": 15.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-3-5-haiku-20241022",
            "provider": "anthropic",
            "price_in": 0.8,
            "price_out": 4.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-3-opus-20240229",
            "provider": "anthropic",
            "price_in": 15.0,
            "price_out": 75.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-sonnet-5",
            "provider": "anthropic",
            "price_in": 2.0,
            "price_out": 10.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-sonnet-4-6",
            "provider": "anthropic",
            "price_in": 3.0,
            "price_out": 15.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-opus-5",
            "provider": "anthropic",
            "price_in": 5.0,
            "price_out": 25.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-opus-4-8",
            "provider": "anthropic",
            "price_in": 5.0,
            "price_out": 25.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
        {
            "id": "claude-haiku-4-5",
            "provider": "anthropic",
            "price_in": 1.0,
            "price_out": 5.0,
            "api_key_env": "ANTHROPIC_API_KEY",
        },
    ],
    "openai": [
        {
            "id": "gpt-4o",
            "provider": "openai",
            "price_in": 2.5,
            "price_out": 10.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-4o-mini",
            "provider": "openai",
            "price_in": 0.15,
            "price_out": 0.6,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "o1",
            "provider": "openai",
            "price_in": 15.0,
            "price_out": 60.0,
            "api_key_env": "OPENAI_API_KEY",
            "capability_score": 0.6,
        },
        {
            "id": "o3-mini",
            "provider": "openai",
            "price_in": 1.1,
            "price_out": 4.4,
            "api_key_env": "OPENAI_API_KEY",
            "capability_score": 0.5,
        },
        {
            "id": "o4-mini",
            "provider": "openai",
            "price_in": 1.1,
            "price_out": 4.4,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-4.5-preview",
            "provider": "openai",
            "price_in": 75.0,
            "price_out": 150.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-5.6",
            "provider": "openai",
            "price_in": 4.0,
            "price_out": 20.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-5.2",
            "provider": "openai",
            "price_in": 1.75,
            "price_out": 14.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-5-mini",
            "provider": "openai",
            "price_in": 0.25,
            "price_out": 2.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-5.1-codex",
            "provider": "openai",
            "price_in": 1.25,
            "price_out": 10.0,
            "api_key_env": "OPENAI_API_KEY",
        },
        {
            "id": "gpt-4.1",
            "provider": "openai",
            "price_in": 2.0,
            "price_out": 8.0,
            "api_key_env": "OPENAI_API_KEY",
        },
    ],
    "google": [
        {
            "id": "gemini-2.5-pro",
            "provider": "google",
            "price_in": 1.25,
            "price_out": 10.0,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-2.5-flash",
            "provider": "google",
            "price_in": 0.3,
            "price_out": 2.5,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-2.0-flash",
            "provider": "google",
            "price_in": 0.1,
            "price_out": 0.4,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-1.5-pro",
            "provider": "google",
            "price_in": 1.25,
            "price_out": 5.0,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-1.5-flash",
            "provider": "google",
            "price_in": 0.075,
            "price_out": 0.3,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-3.5-flash",
            "provider": "google",
            "price_in": 1.5,
            "price_out": 9.0,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-3.5-flash-lite",
            "provider": "google",
            "price_in": 0.3,
            "price_out": 2.5,
            "api_key_env": "GOOGLE_API_KEY",
        },
        {
            "id": "gemini-3.1-pro-preview",
            "provider": "google",
            "price_in": 2.0,
            "price_out": 12.0,
            "api_key_env": "GOOGLE_API_KEY",
        },
    ],
    "mistral": [
        {
            "id": "mistral-large-latest",
            "provider": "mistral",
            "price_in": 0.5,
            "price_out": 1.5,
            "api_key_env": "MISTRAL_API_KEY",
        },
        {
            "id": "mistral-small-latest",
            "provider": "mistral",
            "price_in": 0.15,
            "price_out": 0.6,
            "api_key_env": "MISTRAL_API_KEY",
        },
        {
            "id": "codestral-2508",
            "provider": "mistral",
            "price_in": 0.3,
            "price_out": 0.9,
            "api_key_env": "MISTRAL_API_KEY",
        },
        {
            "id": "ministral-8b-latest",
            "provider": "mistral",
            "price_in": 0.15,
            "price_out": 0.15,
            "api_key_env": "MISTRAL_API_KEY",
        },
        {
            "id": "devstral-2512",
            "provider": "mistral",
            "price_in": 0.4,
            "price_out": 2.0,
            "api_key_env": "MISTRAL_API_KEY",
        },
    ],
    "deepseek": [
        {
            "id": "deepseek-chat",
            "provider": "deepseek",
            "price_in": 0.28,
            "price_out": 0.42,
            "api_key_env": "DEEPSEEK_API_KEY",
        },
        {
            "id": "deepseek-reasoner",
            "provider": "deepseek",
            "price_in": 0.28,
            "price_out": 0.42,
            "api_key_env": "DEEPSEEK_API_KEY",
            "capability_score": 0.5,
        },
        {
            "id": "deepseek-v3.2",
            "provider": "deepseek",
            "price_in": 0.28,
            "price_out": 0.4,
            "api_key_env": "DEEPSEEK_API_KEY",
        },
        {
            "id": "deepseek-v4-flash",
            "provider": "deepseek",
            "price_in": 0.44,
            "price_out": 1.32,
            "api_key_env": "DEEPSEEK_API_KEY",
        },
        {
            "id": "deepseek-v4-pro",
            "provider": "deepseek",
            "price_in": 1.32,
            "price_out": 3.96,
            "api_key_env": "DEEPSEEK_API_KEY",
        },
    ],
    "groq": [
        {
            "id": "llama-3.3-70b-versatile",
            "provider": "groq",
            "price_in": 0.59,
            "price_out": 0.79,
            "api_key_env": "GROQ_API_KEY",
        },
        {
            "id": "llama-3.1-8b-instant",
            "provider": "groq",
            "price_in": 0.05,
            "price_out": 0.08,
            "api_key_env": "GROQ_API_KEY",
        },
        {
            "id": "mixtral-8x7b-32768",
            "provider": "groq",
            "price_in": 0.24,
            "price_out": 0.24,
            "api_key_env": "GROQ_API_KEY",
        },
        {
            "id": "deepseek-r1-distill-llama-70b",
            "provider": "groq",
            "price_in": 0.75,
            "price_out": 0.99,
            "api_key_env": "GROQ_API_KEY",
        },
    ],
    "openrouter": [
        {
            "id": "openrouter/auto",
            "provider": "openrouter",
            "price_in": 1.0,
            "price_out": 2.0,
            "api_key_env": "OPENROUTER_API_KEY",
        },
        {
            "id": "anthropic/claude-3.5-sonnet",
            "provider": "openrouter",
            "price_in": 3.0,
            "price_out": 15.0,
            "api_key_env": "OPENROUTER_API_KEY",
        },
        {
            "id": "openai/gpt-4o",
            "provider": "openrouter",
            "price_in": 2.5,
            "price_out": 10.0,
            "api_key_env": "OPENROUTER_API_KEY",
        },
        {
            "id": "deepseek/deepseek-r1",
            "provider": "openrouter",
            "price_in": 0.55,
            "price_out": 2.19,
            "api_key_env": "OPENROUTER_API_KEY",
        },
        {
            "id": "google/gemini-2.5-flash",
            "provider": "openrouter",
            "price_in": 0.30,
            "price_out": 2.50,
            "api_key_env": "OPENROUTER_API_KEY",
        },
    ],
    "together": [
        {
            "id": "togethercomputer/llama-3.3-70b-instruct",
            "provider": "together",
            "price_in": 0.88,
            "price_out": 0.88,
            "api_key_env": "TOGETHER_API_KEY",
        },
        {
            "id": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
            "provider": "together",
            "price_in": 0.88,
            "price_out": 0.88,
            "api_key_env": "TOGETHER_API_KEY",
        },
        {
            "id": "deepseek-ai/DeepSeek-R1",
            "provider": "together",
            "price_in": 0.55,
            "price_out": 2.19,
            "api_key_env": "TOGETHER_API_KEY",
        },
        {
            "id": "deepseek-ai/DeepSeek-V3",
            "provider": "together",
            "price_in": 0.14,
            "price_out": 0.28,
            "api_key_env": "TOGETHER_API_KEY",
        },
    ],
    "xai": [
        {
            "id": "grok-2-latest",
            "provider": "xai",
            "price_in": 2.0,
            "price_out": 10.0,
            "api_key_env": "XAI_API_KEY",
        },
        {
            "id": "grok-2-vision-latest",
            "provider": "xai",
            "price_in": 2.0,
            "price_out": 10.0,
            "api_key_env": "XAI_API_KEY",
        },
        {
            "id": "grok-beta",
            "provider": "xai",
            "price_in": 5.0,
            "price_out": 15.0,
            "api_key_env": "XAI_API_KEY",
        },
        {
            "id": "grok-4.5",
            "provider": "xai",
            "price_in": 2.0,
            "price_out": 6.0,
            "api_key_env": "XAI_API_KEY",
        },
        {
            "id": "grok-4-6",
            "provider": "xai",
            "price_in": 2.0,
            "price_out": 6.0,
            "api_key_env": "XAI_API_KEY",
        },
    ],
}
PRESETS.update(FALLBACK_PRESETS)

PRESET_ORDER = [
    "custom",
    "openai",
    "anthropic",
    "google",
    "mistral",
    "deepseek",
    "groq",
    "openrouter",
    "together",
    "xai",
    "llmgateway",
    "devpass",
]

# Compatibility exports from the original ``model_presets`` module.  Keep
# these derived from PRESETS so the catalog cannot silently drift from the
# preset data when a provider adds or removes a model.
DEFAULT_MODELS = [row["id"] for rows in PRESETS.values() for row in rows]
MODEL_IDS = list(DEFAULT_MODELS)
